name: astrowillman1
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - astropy=5.3.4
  - asttokens=2.4.1
  - blas=1.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.12
  - cfitsio=4.4.0
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.2.0
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.5.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - galpy=1.9.2
  - gsl=2.7
  - healpy=1.16.6
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - iniconfig=2.0.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - jedi=0.19.1
  - jinja2=3.1.6
  - jpeg=9e
  - jupyter_client=8.6.1
  - jupyter_core=5.5.0
  - kiwisolver=1.4.4
  - krb5=1.21.3
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=8.7.1
  - libcxx=16.0.6
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=14.2.0
  - libnghttp2=1.58.0
  - libpng=1.6.39
  - libsodium=1.0.18
  - libsqlite=3.45.2
  - libssh2=1.11.0
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=3.0.3
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.4.0
  - openssl=3.6.0
  - packaging=23.2
  - pandas=2.2.1
  - parso=0.8.4
  - patsy=1.0.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=23.3.1
  - platformdirs=4.2.0
  - pluggy=1.6.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyerfa=2.0.0
  - pygments=2.17.2
  - pyparsing=3.0.9
  - pytest=8.4.0
  - pytest-runner=6.0.0
  - python=3.12.2
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.12
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - readline=8.2
  - scipy=1.12.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - statsmodels=0.14.4
  - tbb=2021.8.0
  - tk=8.6.13
  - tomli=2.2.1
  - tornado=6.3.3
  - traitlets=5.14.2
  - typing_extensions=4.11.0
  - tzdata=2024a
  - wcwidth=0.2.13
  - wheel=0.41.2
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - corner==2.2.2
      - cython==3.0.10
      - dustmaps==1.0.14
      - dynesty==2.1.5
      - emcee==3.1.4
      - gala==1.8.1
      - h5py==3.13.0
      - idna==3.10
      - mpmath==1.3.0
      - progressbar2==4.5.0
      - python-utils==3.9.1
      - requests==2.32.3
      - sfdmap==0.1.1
      - sympy==1.14.0
      - tqdm==4.67.0
      - urllib3==2.4.0
prefix: /Users/camillechiu/opt/anaconda3/envs/astrowillman1
